### PR TITLE
release 100%

### PR DESCRIPTION
**Pull request by GamerBlue208**
it has been to rocky of a start for all *that* to be counted, so now this is the first release, everything should work as espected, report any bugs you find, i'll be happy to fix them.

### CODE REVIEW

**Comment by NormTurtle** [comment]
i can't test im stuck to window -_-

**Comment by NormTurtle** [comment]
anyways , here is ubuntu 20.4.5 lts  test 
image

❌  failed  IDK why 😞

**Comment by GamerBlue208** [comment]
uh, its an error i did, i putted two && in a row, it should be fixed already

**Comment by GamerBlue208** [comment]
and if you want to report a bug, go to the issues page

**Pull request merged**
